language: ruby
rvm:
  - 2.6  
  
addons:
  ssh_known_hosts:
  - www270.your-server.de  

branches:
  only:
    - master

install:
  - bundle update --jobs=3 --retry=3
  
script: 
  - gradle getIli2fmeVersion buildSite 
deploy:
  - provider: script
    skip_cleanup: true
    script: gradle -Dsite_pwd=${site_pwd} -Dsite_usr=iliyfm -Dsite_url=www270.your-server.de uploadSite
    on:
      branch: master
