language: ruby
rvm:
  - 2.6  
  
branches:
  only:
    - master

script: 
  - gradle buildSite 
deploy:
  - provider: script
    skip_cleanup: true
    script: gradle -Dsite_pwd=${site_pwd} -Dsite_usr=iliyfm -Dsite_url=www270.your-server.de uploadSite
    on:
      branch: master
