title: ili2fme
description: An INTERLIS-plugin for FME 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ili2fme.ch" # the base hostname & protocol for your site, e.g. http://example.com

theme: minimal-mistakes-jekyll

asciidoctor:
  base_dir: :docdir
  attributes:
    imagesdir: '{site-baseurl}'  
    
permalink: /:title:output_ext

defaults:
  - scope:
      path: ""
    values:
      layout: single
      
collections:
  posts:
    output: true
    permalink: /:collection/:year/:title:output_ext